# Generated by Django 4.1.7 on 2023-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_rename_user_id_todolist_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
