# Generated by Django 4.1.7 on 2023-05-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_rename_user_users_alter_todolist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'High'), ('2', 'Medium'), ('3', 'Login')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
