# Generated by Django 4.1.7 on 2023-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_alter_todolist_date_alter_todolist_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[(0, 'Normal'), (1, 'High'), (2, 'Medium'), (3, 'Login')], default=0, max_length=20),
        ),
    ]
